#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_institutos:
    path: /institutos/
    controller: App\Controller\InstitutoController::index
app_search:
    path: /institutos/search
    controller: App\Controller\SearchController::search
app_carreras:
    path: /carreras
    controller: App\Controller\CarreraController::index
app_preinscripcion:
    path: /preinscripcion
    controller: App\Controller\PreinscripcionController::index
    